apiVersion: v1
kind: ConfigMap
metadata:
    name: scraper
    namespace: scraper
data:
    KAFKA_BROKERS: kafka.scraper.svc.cluster.local:9092
    REDIS_URL: redis://redis.scraper.svc.cluster.local:6379
    METRICS_PORT: "9090"
    SEED_URLS: "https://en.wikipedia.org/wiki/Main_Page,https://en.wikipedia.org/wiki/Lists_of_websites,https://news.ycombinator.com,https://curlie.org,https://github.com/explore,https://www.reddit.com,https://stackoverflow.com,https://www.bbc.com,https://www.cnn.com,https://www.mozilla.org,https://www.python.org,https://nodejs.org,https://developer.mozilla.org,https://archive.org,https://stackexchange.com,https://www.reuters.com,https://www.theguardian.com,https://www.npr.org,https://arstechnica.com,https://www.theverge.com,https://www.wired.com,https://techcrunch.com,https://www.fandom.com,https://www.imdb.com,https://www.npmjs.com,https://gitlab.com"
    CRAWL_ALLOWED_TLDS: "com,net,org,io,ru,de,fr,uk,edu,gov,co,info,biz"
    RATE_LIMIT_PER_SECOND: "40"
